org: frova
app: aws-scrapping
service: aws-scrapping
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
    memorySize: 512
    timeout: 30

plugins:
  - serverless-plugin-typescript
